[project]
name = "agentic-ai-agent4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "dot>=0.3.0",
    "env>=0.1.0",
    "openai>=1.99.9",
    "openai-agents==0.1.0",
]
